version: '2'
services:
  frenchgeo-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/frenchGeo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frenchGeo
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
